version: '3.8'
services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js